pygments:    true
permalink:   /p/:title/
include: [".htaccess"]
exclude: [sass, style.scss, readme.md, config.rb]

author :
  name : James King
  email : j@lostwith.me
  github : sorakasumi
  twitter : sorakasumi

baseurl: 
url: http://lostwith.me
category_dir: /c/

markdown: rdiscount